apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: linuxserver/jackett
    newTag: v0.24.2738-ls44
  - name: linuxserver/sonarr
    newTag: 4.0.20.3014-ls326
  - name: linuxserver/radarr
    newTag: 6.4.4.10685-ls318
  - name: linuxserver/bazarr
    newTag: v1.6.2-ls366
  - name: linuxserver/transmission
    newTag: 4.1.3-r0-ls363
  - name: emby/embyserver
    newTag: 4.11.0.4-amd64
  - name: linuxserver/prowlarr
    newTag: 2.6.5.5623-ls162
  - name: lscr.io/linuxserver/readarr
    newTag: nightly-0.4.16.2788-ls395
  - name: lscr.io/linuxserver/jellyfin
    newTag: 12.1ubu2604-ls51
  - name: lscr.io/linuxserver/kavita
    newTag: v0.9.1.4-ls126
  - name: lscr.io/linuxserver/lidarr
    newTag: 3.1.0.4875-ls42
