apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: linuxserver/jackett
    newTag: v0.24.1731-ls382
  - name: linuxserver/sonarr
    newTag: 4.0.17.2952-ls308
  - name: linuxserver/radarr
    newTag: 6.1.1.10360-ls300
  - name: linuxserver/bazarr
    newTag: v1.5.6-ls345
  - name: linuxserver/transmission
    newTag: 4.1.1-r1-ls340
  - name: lscr.io/linuxserver/qbittorrent
    newTag: 5.1.4-r3-ls451
  - name: emby/embyserver
    newTag: 4.10.0.10-amd64
  - name: linuxserver/prowlarr
    newTag: 2.3.5.5327-ls143
  - name: lscr.io/linuxserver/readarr
    newTag: nightly-0.4.16.2788-ls395
  - name: lscr.io/linuxserver/jellyfin
    newTag: 10.11.8ubu2404-ls29
  - name: lscr.io/linuxserver/kavita
    newTag: v0.8.9.1-ls106
  - name: lscr.io/linuxserver/lidarr
    newTag: 3.1.0.4875-ls25
  - name: santiagosayshey/profilarr
    newTag: v1.1.4
resources:
  - ../../base
  - ../../base/cluster
