apiVersion: v1
kind: Secret
metadata:
  name: bazarr-credentials
  namespace: media
type: Opaque
stringData:
  BAZARR_API_KEY: "168992260e408889b7173e8015b4bbd2"
  BAZARR_AUTH_PASSWORD: "570c0e43355144c7f8d2fa33f66b704b"
  BAZARR_FLASK_SECRET: "977f2f868958dba31c236e7b2767b1b0b9c9b960c129ba123d2f9d775f14630a"
  OPENSUBTITLES_USER: "antoniocanelas@gmail.com"
  OPENSUBTITLES_PASS: "Camelox00."
