apiVersion: v1
kind: Service
metadata:
  name: bazarr
  labels:
    app: media
spec:
  ports:
  - port: 6767
    protocol: TCP
    targetPort: 6767
    name: webui
  selector:
    app: media
    run: bazarr
