---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: qbittorrent
  name: qbittorrent
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      run: qbittorrent
  template:
    metadata:
      labels:
        run: qbittorrent
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: chown
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /config && chown -R 1000:1000 /downloads && chown -R 1000:1000 /media && chown -R 1000:1000 /watch"]
        volumeMounts:
        - mountPath: /config
          name: media-config
          subPath: qbittorrent
        - mountPath: /downloads
          name: media
          subPath: downloads
        - mountPath: /watch
          name: media
          subPath: watch
        - mountPath: /media
          name: media
          subPath: media
      containers:
      - name: qbittorrent
        image: lscr.io/linuxserver/qbittorrent
        env:
        - name: TZ
          value: Pacific/Auckland
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: WEBUI_PORT
          value: "8080"
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        ports:
        - containerPort: 8080
          name: webui
          protocol: TCP
        - containerPort: 6881
          name: qbittorrent-tcp
          protocol: TCP
        - containerPort: 6881
          name: qbittorrent-udp
          protocol: UDP
        volumeMounts:
          - mountPath: /config
            name: media-config
            subPath: qbittorrent
          - mountPath: /downloads
            name: media
            subPath: downloads
          - mountPath: /watch
            name: media
            subPath: watch
          - mountPath: /media
            name: media
            subPath: media
      volumes:
        - name: media-config
          persistentVolumeClaim:
            claimName: media-config-pvc
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc
