apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  labels:
    app: media
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: webui
  - port: 6881
    protocol: TCP
    targetPort: 6881
    name: qbittorrent-tcp
  - port: 6881
    protocol: UDP
    targetPort: 6881
    name: qbittorrent-udp
  selector:
    app: media
    run: qbittorrent
