apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: changedetection-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
