apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: argocd

resources:
- namespace.yaml
- application.yaml
- ingress-route.yaml
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.7.18

patches:
- path: argo-server_patch.yaml
