apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.5.5
- namespace.yaml
- application.yaml
- htpc-application.yaml
- ingress-route.yaml

namespace: argocd

patches:
- path: argo-server_patch.yaml

images:
- name: redis
  newName: arm64v8/redis
  newTag: 7.0.5-alpine
