---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: jellyfin
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      run: jellyfin
  template:
    metadata:
      labels:
        run: jellyfin
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - env:
        - name: TZ
          value: Europe/Lisbon
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: JELLYFIN_PublishedServerUrl
          value: "https://telheira.tplinkdns.com/jellyfin"
        image: lscr.io/linuxserver/jellyfin:arm64v8-latest
        name: jellyfin
        ports:
        - containerPort: 8096
          name: webui
          protocol: TCP
        - containerPort: 8920
          name: webui-ssl
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: webui
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: webui
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - mountPath: /config 
          name: config
          subPath: config/jellyfin
        - mountPath: /tv 
          name: media
          subPath: media/tv
        - mountPath: /movies 
          name: media
          subPath: media/movies
#        - mountPath: /books
#          name: media
#          subPath: media/books
#        - mountPath: /music
#          name: media
#          subPath: media/music
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: ssd-config-pvc
        - name: media
          persistentVolumeClaim:
            claimName: nas-media-pvc
