apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: htpc

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app: htpc

resources:
- namespace.yaml
- pvc.yaml
- radarr
- sonarr
- prowlarr
- transmission
- ingress-route.yaml
#- jackett
#- bazarr
#- readarr
#- jellyfin
#- kavita
#- lidarr

patches:
- path: env_variables_patch.yaml
