apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app: media

#- transmission
#- profilarr
resources:
- namespace.yaml
- ingress-route-external.yaml
- ingress-route-homeassistant-external.yaml
- ingress-route-plex-external.yaml
- middlewares.yaml
- external-services.yaml
- nas-storage.yaml
- ssd-storage.yaml
- qbittorrent
- prowlarr
- radarr
- sonarr
- bazarr
- tailscale
#- jackett
#- readarr
#- jellyfin
#- kavita
#- lidarr

patches:
- patch: |-
    - op: add
      path: /spec/selector
      value:
        external-backend: "true"
  target:
    kind: Service
    name: homeassistant-external
    version: v1
- patch: |-
    - op: add
      path: /spec/selector
      value:
        external-backend: "true"
  target:
    kind: Service
    name: jellyfin-external
    version: v1
- patch: |-
    - op: add
      path: /spec/selector
      value:
        external-backend: "true"
  target:
    kind: Service
    name: plex-external
    version: v1
