apiVersion: v1
kind: PersistentVolume
metadata:
  name: htpc-home
spec:
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume1/arr-data
    server: 192.168.0.200
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: htpc-home-pvc
  namespace: htpc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Gi
  volumeName: htpc-home
  storageClassName: ""