---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: prowlarr
  name: prowlarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      run: prowlarr
  template:
    metadata:
      labels:
        run: prowlarr
    spec:
      securityContext:
        fsGroup: 1000    
      initContainers:
      - name: config
        image: busybox
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        command: ["sh", "-c"]
        args:
        - |
          if [ ! -f /config/config.xml ]; then
            cat <<'EOF' > /config/config.xml
            <Config>
              <UrlBase>/prowlarr</UrlBase>
              <LogLevel>debug</LogLevel>
              <BindAddress>*</BindAddress>
              <Port>9696</Port>
              <SslPort>6969</SslPort>
              <EnableSsl>False</EnableSsl>
              <LaunchBrowser>True</LaunchBrowser>
              <AuthenticationMethod>Forms</AuthenticationMethod>
              <AuthenticationRequired>DisabledForLocalAddresses</AuthenticationRequired>
              <Branch>master</Branch>
              <SslCertPath></SslCertPath>
              <SslCertPassword></SslCertPassword>
              <InstanceName>Prowlarr</InstanceName>
              <UpdateMechanism>Docker</UpdateMechanism>
            </Config>
            EOF
          fi
        volumeMounts: 
        - mountPath: /config 
          name: config
          subPath: prowlarr
      containers:
      - env:
        - name: TZ
          value: Europe/Lisbon
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        image: linuxserver/prowlarr
        name: prowlarr
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        ports:
        - containerPort: 9696
          name: webui
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - curl "http://localhost:9696/prowlarr/api/v1/health?ApiKey=$(sed -ne '/ApiKey/{s/.*<ApiKey>\(.*\)<\/ApiKey>.*/\1/p;q;}' </config/config.xml)"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - curl "http://localhost:9696/prowlarr/api/v1/system/status?ApiKey=$(sed -ne '/ApiKey/{s/.*<ApiKey>\(.*\)<\/ApiKey>.*/\1/p;q;}' </config/config.xml)"
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts: 
        - mountPath: /config 
          name: config
          subPath: prowlarr
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: ssd-config-pvc
