apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  labels:
    app: media
spec:
  ports:
  - port: 9696
    protocol: TCP
    targetPort: 9696
    name: webui
  selector:
    app: media
    run: prowlarr
