---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: sonarr
  name: sonarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      run: sonarr
  template:
    metadata:
      labels:
        run: sonarr
    spec:
      securityContext:
        # runAsUser: 1000
        # runAsGroup: 1000
        fsGroup: 1000    
      initContainers:
      - name: chown
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /config && chown -R 1000:1000 /tv"]
        volumeMounts:
          - mountPath: /config
            name: htpc-home
            subPath: config/sonarr
          - mountPath: /tv
            name: htpc-home
            subPath: torrents
            # TODO remove /downloads
          - mountPath: /downloads
            name: htpc-home
            subPath: downloads
      - name: config
        image: busybox
        command: ["sh", "-c"]
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        args:
          - "echo start;[[ ! -f /config/config.xml ]] && echo '<Config><UrlBase>/sonarr</UrlBase></Config>'> /config/config.xml;echo end;"
        volumeMounts:
          - mountPath: /config
            name: htpc-home
            subPath: config/sonarr
          - mountPath: /tv
            name: htpc-home
            subPath: torrents
            # TODO remove /downloads
          - mountPath: /downloads
            name: htpc-home
            subPath: downloads
      containers:
      - env:
        - name: TZ
          value: Pacific/Auckland
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        image: linuxserver/sonarr
        name: sonarr
        ports:
        - containerPort: 8989
          name: webui
        startupProbe:
          tcpSocket:
            port: 8989
          failureThreshold: 30
          periodSeconds: 10
          timeoutSeconds: 2
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - curl "http://localhost:8989/sonarr/api/health?ApiKey=$(sed -ne '/ApiKey/{s/.*<ApiKey>\(.*\)<\/ApiKey>.*/\1/p;q;}' </config/config.xml)"
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 8
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - curl "http://localhost:8989/sonarr/api/system/status?ApiKey=$(sed -ne '/ApiKey/{s/.*<ApiKey>\(.*\)<\/ApiKey>.*/\1/p;q;}' </config/config.xml)"
          initialDelaySeconds: 20
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 8
        volumeMounts:
        - mountPath: /config
          name: htpc-home
          subPath: config/sonarr
        - mountPath: /tv
          name: htpc-home
          subPath: torrents
          # TODO remove /downloads
        - mountPath: /downloads
          name: htpc-home
          subPath: downloads
      volumes:
        - name: htpc-home
          persistentVolumeClaim:
            claimName: htpc-home-pvc
