apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: media
    run: sonarr
  name: sonarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media
      run: sonarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: media
        run: sonarr
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: config
        image: busybox
        command:
        - sh
        - -c
        args:
        - |
          if [ ! -f /config/config.xml ]; then
            printf '%s\n' \
              '<Config>' \
              '  <UrlBase>/sonarr</UrlBase>' \
              '  <LogLevel>debug</LogLevel>' \
              '  <BindAddress>*</BindAddress>' \
              '  <Port>8989</Port>' \
              '  <SslPort>9898</SslPort>' \
              '  <EnableSsl>False</EnableSsl>' \
              '  <LaunchBrowser>True</LaunchBrowser>' \
              '  <AuthenticationMethod>Forms</AuthenticationMethod>' \
              '  <AuthenticationRequired>DisabledForLocalAddresses</AuthenticationRequired>' \
              '  <Branch>main</Branch>' \
              '  <SslCertPath></SslCertPath>' \
              '  <SslCertPassword></SslCertPassword>' \
              '  <InstanceName>Sonarr</InstanceName>' \
              '  <UpdateMechanism>Docker</UpdateMechanism>' \
              '</Config>' \
              > /config/config.xml
          fi
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        volumeMounts:
        - mountPath: /config
          name: config
          subPath: sonarr
      containers:
      - name: sonarr
        env:
        - name: TZ
          value: Europe/Lisbon
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        image: linuxserver/sonarr:arm64v8-latest
        ports:
        - containerPort: 8989
          name: webui
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        startupProbe:
          tcpSocket:
            port: 8989
          failureThreshold: 30
          periodSeconds: 10
          timeoutSeconds: 2
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - curl "http://localhost:8989/sonarr/api/health?ApiKey=$(sed -ne '/ApiKey/{s/.*<ApiKey>\(.*\)<\/ApiKey>.*/\1/p;q;}'
              </config/config.xml)"
          failureThreshold: 8
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - curl "http://localhost:8989/sonarr/api/system/status?ApiKey=$(sed -ne
              '/ApiKey/{s/.*<ApiKey>\(.*\)<\/ApiKey>.*/\1/p;q;}' </config/config.xml)"
          failureThreshold: 8
          initialDelaySeconds: 20
          periodSeconds: 15
          timeoutSeconds: 5
        volumeMounts:
          - mountPath: /config
            name: config
            subPath: sonarr
          - mountPath: /tv
            name: media
            subPath: tv
          - mountPath: /downloads
            name: downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: ssd-config-pvc
        - name: downloads
          persistentVolumeClaim:
            claimName: ssd-downloads-pvc
        - name: media
          persistentVolumeClaim:
            claimName: nas-media-pvc
