apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    app: media
spec:
  ports:
  - port: 8989
    protocol: TCP
    targetPort: 8989
    name: webui
  selector:
    app: media
    run: sonarr
